### PR TITLE
LMDE upgrade info and major target_codenames

### PR DESCRIPTION
**Pull request by carlosmintfan**

### CODE REVIEW

**Comment by carlosmintfan** [comment]
@clefebvre @mtwebster from where should I download screenshots for major releases? https://www.linuxmint.com/pictures/screenshots/elsie/cinnamon.png, for example, is 1920x1200 pixels, while /usr/share/mint-upgrade-info/uma/cinnamon.png is only 526 x 339 and also has transparent margins...

**Comment by carlosmintfan** [comment]
Should I use the nemo action "Make a thumbnail" from mint-dev-tools?

**Comment by carlosmintfan** [comment]
And what about "Add a shadow"? EDIT this seems to be used for screenshots you publish on your blog.

**Comment by clefebvre** [comment]
We use thumb_cinnamon.png rather than cinnamon.png, it's produced by the Make a Thumbnail nemo action indeed.

**Comment by clefebvre** [comment]
https://www.linuxmint.com/pictures/screenshots/elsie/thumb_cinnamon.png

**Comment by clefebvre** [comment]
Why are you adding target_codename?

**Comment by carlosmintfan** [comment]
"I'm working on integrating major upgrades into mintUpdate and this helps for that."
@clefebvre Do you remember https://github.com/linuxmint/lmde6-beta/issues/18 and https://github.com/linuxmint/lmde6-beta/issues/36? It seems you saw my last comment to 18 because you answered the Romeo discussion, but you didn't answer! I know I have been spamming you…and maybe losed trust this way… anyway, I added target_codenames to the major upgrades (like the minor ones already have) because mint-release-upgrade uses it. I had started this and that way (integrating the mintupgrade stuff directly in mint-release-upgrade, making mintupgrade use mint-upgrade-info) and my last try was starting mintupgrade from mint-release-upgrade for major upgrades (after the user has read the release notes/new features). But a GTK assistant doesn't seem usable for that. It may work when launched from a terminal, but not when launched graphically.
Anyway, why didn't you add the LMDE upgrade info in the past? :) Could you do that for future LMDE releases?

**Comment by carlosmintfan** [comment]
And the major release screenshots are also for that: mint-release-upgrade. But we would have to implement something different than a GTK assistant if we want that.

**Comment by clefebvre** [comment]
OK you're mixing different things here.

I'm not sure it's a good idea to turn mintupdate into a major upgrader, it already does a lot of different things and is already quite complex.

If it was you'd start with a PR on mintupdate, and a separate PR here. You can't just merge things for future changes...

**Comment by carlosmintfan** [comment]
The major upgrades can still be done by mintupgrade, mintUpdate should just show the introduction with the screenshot and the new releases/new features links. The problem is just that this doesn't work with GTK assistant: When I click on apply, I want the assistant to close and mintupgrade to open. But that just doesn't work (but it does when launched from a terminal... yes I use pkexec). Anyway, mint-release-upgrade has to be improved anyway because you always get that stupid "is not responding" window just because the assistant is not responding yeah because it waits for the synaptic subprocess to finish. Maybe you can fix that before opening the upgrade path to 21.3?

**Comment by carlosmintfan** [comment]
You can close the PR when you've read the comment (and answered the part about the not responding warnings), I'll make a new with the LMDE upgrade info then (or you can just add it yourself if you want).

**Comment by crhy** [comment]
Hey guys!  A little offtopic, but here's my review of the Mint MATE beta.  https://rumble.com/v45simc-linux-mint-mate-21.3-beta-review.html

**Pull request closed without merging**
