### PR TITLE
Add upgrade info for 20.3 -> 21

### PR DESCRIPTION
**Pull request by carlosmintfan**

### CODE REVIEW

**Comment by carlosmintfan** [comment]
@clefebvre

**Comment by carlosmintfan** [comment]
@clefebvre Please merge this, you have already opened the path for 21>21.1 now, please merge that too, it's long overdue :)

**Comment by mtwebster** [comment]
I don't think the -major files are used anymore. The others are checked in mintupdate (rel_upgrade.py).

**Comment by carlosmintfan** [comment]
The -major folders are necessary for showing people who don't read the mint blog that an update is available.
PLEASE merge this and also create the LMDE 4>5 upgrade info!
Thanks. Please do it :)

**Pull request closed without merging**
